name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Setup Python 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.5"

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # 4) Run tests
      - name: Run tests with pytest
        run: pytest test.py
