name: ci-image-classification

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-dvc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[s3]" mlflow

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Configure DVC remote
        run: |
          dvc remote add -f aws ${{ secrets.DVC_S3_URL }}
          dvc remote default aws

      - name: Run unit tests
        run: pytest -q --disable-warnings --maxfail=1

      - name: Pull latest DVC data
        run: dvc pull

      - name: Run DVC pipeline
        run: dvc repro

      - name: Push DVC artifacts to S3
        run: dvc push

      - name: Show metrics
        run: cat reports/metrics.json || echo "No metrics.json found"

      - name: Upload metrics artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: reports/metrics.json
